import React, { useCallback, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { api, websocketUrl } from "./api.js";
import "@fontsource-variable/inter";
import "./viz.css";
import "./styles.css";
import DemoApp from "./DemoApp.jsx";
import MineMap from "./MineMap.jsx";
import RiskProjection, { mostUrgent } from "./RiskProjection.jsx";

const riskOrder = { normal: 0, warning: 1, high: 2, critical: 3 };
const formatTime = (value) => value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "—";
const riskLabel = (value) => value ? value[0].toUpperCase() + value.slice(1) : "Unknown";
const classForRisk = (value) => `risk-${value || "normal"}`;

function MetricCard({ label, value, detail, tone = "default" }) { return <article className={`metric-card ${tone}`}><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</article>; }
function StatusDot({ status }) { return <span className={`status-dot ${status === "online" ? "online" : "offline"}`}><i />{status || "offline"}</span>; }
function Empty({ children }) { return <div className="empty">{children}</div>; }

function SensorData({ data }) {
  const entries = Object.entries(data || {}).filter(([key]) => !["numeric", "sourceTimestamp"].includes(key));
  if (!entries.length) return <span className="muted">No telemetry yet</span>;
  return <div className="sensor-grid">{entries.map(([key, value]) => <div className="sensor" key={key}><span>{key.replaceAll("_", " ")}</span><b>{typeof value === "object" && value !== null ? Object.entries(value).map(([child, childValue]) => <em key={child}>{child}: {String(childValue)}</em>) : String(value)}</b></div>)}</div>;
}

function App() {
  const [state, setState] = useState(null); const [mine, setMine] = useState(null); const [locations, setLocations] = useState([]); const [devices, setDevices] = useState([]); const [alerts, setAlerts] = useState([]); const [assessment, setAssessment] = useState(null); const [system, setSystem] = useState(null); const [selectedDevice, setSelectedDevice] = useState(null); const [selectedLocation, setSelectedLocation] = useState(null); const [deviceDetail, setDeviceDetail] = useState(null); const [history, setHistory] = useState(null); const [locationDetail, setLocationDetail] = useState(null); const [locationHistory, setLocationHistory] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [lastEvent, setLastEvent] = useState("Connecting"); const [projectionHistory, setProjectionHistory] = useState([]);

  const refresh = useCallback(async () => {
    try { setError(""); const [nextState, nextMine, nextLocations, nextDevices, nextAlerts, nextAssessment, nextSystem] = await Promise.all([api.state(), api.mine(), api.locations(), api.devices(), api.alerts(), api.assessment(), api.system()]); setState(nextState); setMine(nextMine); setLocations(nextLocations); setDevices(nextDevices); setAlerts(nextAlerts); setAssessment(nextAssessment); setSystem(nextSystem); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { refresh(); const interval = setInterval(refresh, 30_000); return () => clearInterval(interval); }, [refresh]);
  useEffect(() => { let socket; let reconnect; const connect = () => { socket = new WebSocket(websocketUrl()); socket.onopen = () => setLastEvent("Live"); socket.onmessage = (message) => { try { const event = JSON.parse(message.data); if (event.type !== "connected") { setLastEvent(event.type); refresh(); } } catch { /* Ignore malformed gateway events. */ } }; socket.onclose = () => { setLastEvent("Reconnecting"); reconnect = setTimeout(connect, 3000); }; socket.onerror = () => socket.close(); }; connect(); return () => { clearTimeout(reconnect); socket?.close(); }; }, [refresh]);
  useEffect(() => { if (!selectedDevice) { setDeviceDetail(null); setHistory(null); return; } Promise.all([api.device(selectedDevice), api.deviceHistory(selectedDevice)]).then(([detail, deviceHistory]) => { setDeviceDetail(detail); setHistory(deviceHistory); }).catch((requestError) => setError(requestError.message)); }, [selectedDevice]);
  useEffect(() => { if (!selectedLocation) { setLocationDetail(null); setLocationHistory(null); return; } Promise.all([api.location(selectedLocation), api.locationHistory(selectedLocation)]).then(([detail, locationHistoryData]) => { setLocationDetail(detail); setLocationHistory(locationHistoryData); }).catch((requestError) => setError(requestError.message)); }, [selectedLocation]);

  const urgent = useMemo(() => mostUrgent(state?.devices || []), [state]);
  const charted = urgent || state?.devices?.[0];
  useEffect(() => { if (!charted) { setProjectionHistory([]); return; } api.deviceHistory(charted.deviceId).then((result) => setProjectionHistory(result.rows || [])).catch(() => setProjectionHistory([])); }, [charted?.deviceId, state?.lastUpdated]);
  const onlineCount = state?.summary?.devices?.online ?? devices.filter((device) => device.status === "online").length; const affectedCount = state?.summary?.locations?.affected ?? 0; const overall = state?.overall || { riskLevel: "normal", status: "normal", priority: "normal" }; const selectedStateDevice = useMemo(() => state?.devices?.find((device) => device.deviceId === selectedDevice), [state, selectedDevice]);
  if (loading) return <main className="loading-screen"><div className="loader" /><p>Connecting to Mine Edge Gateway…</p></main>;
  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">M</div><div><strong>Mine Edge</strong><span>Inspector control room</span></div></div><div className="topbar-actions"><span className={`live-pill ${["Live", "Connecting"].includes(lastEvent) || lastEvent.includes(".") ? "is-live" : ""}`}><i />{lastEvent.includes(".") || lastEvent === "Live" ? "Live updates" : lastEvent}</span><button className="button ghost" onClick={refresh}>Refresh</button></div></header>
    <main className="content"><section className="welcome"><div><p className="eyebrow">Mine overview</p><h1>{mine?.name || state?.mine?.name || "Mine"}</h1><p className="subtle">{mine?.location || "Local Raspberry Pi gateway"} · Last update {formatTime(state?.lastUpdated)}</p></div><div className={`risk-banner ${classForRisk(overall.riskLevel)}`}><span>Current risk</span><strong>{riskLabel(overall.riskLevel)}</strong><small>{riskLabel(overall.priority)} priority</small></div></section>
      {error && <div className="error-banner"><strong>Connection issue</strong><span>{error}</span><button onClick={refresh}>Try again</button></div>}
      <MineMap devices={state?.devices || []} selectedDevice={selectedDevice} onSelect={setSelectedDevice} kicker="Spatial view" title="Underground view" subtitle="Every registered location and the devices reporting from it" />
      <RiskProjection device={urgent || state?.devices?.[0]} history={projectionHistory} rules={state?.rules || []} />
      <section className="metrics"><MetricCard label="Devices online" value={`${onlineCount}/${state?.summary?.devices?.total ?? devices.length}`} detail={`${state?.summary?.devices?.offline ?? 0} offline`} tone={onlineCount === (state?.summary?.devices?.total ?? devices.length) ? "good" : "warning"} /><MetricCard label="Affected locations" value={affectedCount} detail={`${state?.summary?.locations?.total ?? locations.length} total locations`} tone={affectedCount ? "danger" : "good"} /><MetricCard label="Telemetry received" value={state?.summary?.telemetryCount ?? 0} detail="Stored readings" /><MetricCard label="ML assessment" value={system?.ml?.available ? "Available" : "Unavailable"} detail={system?.ml?.available ? "Local model active" : "Rules engine continues"} tone={system?.ml?.available ? "good" : "warning"} /></section>
      <section className="main-grid"><div className="panel locations-panel"><div className="panel-heading"><div><p className="eyebrow">Mine layout</p><h2>Locations</h2></div><span className="panel-count">{locations.length} zones</span></div><div className="location-list">{locations.length ? locations.map((location) => { const locationDevices = state?.devices?.filter((device) => device.location.locationId === location.locationId) || []; const affected = locationDevices.some((device) => riskOrder[device.assessment?.riskLevel] > 0); return <button className={`location-row ${selectedLocation === location.locationId ? "selected" : ""}`} key={location.locationId} onClick={() => setSelectedLocation(location.locationId)}><span className={`location-icon ${affected ? "alert" : ""}`}>⌖</span><span className="location-info"><strong>{location.name}</strong><small>{location.zone || "Unassigned zone"}</small></span><span className="location-devices">{locationDevices.length} device{locationDevices.length === 1 ? "" : "s"}</span><span className={`mini-risk ${classForRisk(affected ? "warning" : "normal")}`}>{affected ? "Review" : "Normal"}</span></button>; }) : <Empty>No mine locations registered yet.</Empty>}</div>{selectedLocation && <div className="inline-detail"><div className="detail-heading"><div><span className="eyebrow">Selected location</span><h3>{locationDetail?.name || selectedLocation}</h3></div><button className="close" onClick={() => setSelectedLocation(null)}>×</button></div><p>{locationDetail?.description || "No description configured."}</p><div className="detail-meta">{locationDetail?.zone || "—"} · {locationHistory?.total ?? 0} historical readings</div></div>}</div>
        <div className="panel alerts-panel"><div className="panel-heading"><div><p className="eyebrow">Attention queue</p><h2>Alerts</h2></div><span className="panel-count">{alerts.length}</span></div>{alerts.length ? <div className="alert-list">{alerts.slice(0, 6).map((alert) => <div className={`alert-row ${classForRisk(alert.severity)}`} key={alert.id}><span className="alert-icon">!</span><div><strong>{alert.message}</strong><small>{alert.device_id || "Mine"} · {formatTime(alert.created_at)}</small></div></div>)}</div> : <Empty><span className="empty-check">✓</span>No active alerts. Conditions look normal.</Empty>}</div></section>
      <section className="panel devices-panel"><div className="panel-heading"><div><p className="eyebrow">Field network</p><h2>ESP32 devices</h2></div><span className="panel-count">{devices.length} registered</span></div><div className="table-wrap"><table><thead><tr><th>Device</th><th>Location</th><th>Status</th><th>Battery</th><th>Last telemetry</th><th>Assessment</th><th /></tr></thead><tbody>{(state?.devices || devices).map((device) => <tr className={selectedDevice === device.deviceId ? "active-row" : ""} key={device.deviceId}><td><button className="device-link" onClick={() => setSelectedDevice(device.deviceId)}><span className="device-avatar">⌁</span><span><strong>{device.deviceId}</strong><small>{device.firmwareVersion || "Firmware not reported"}</small></span></button></td><td><strong>{device.location?.name || device.location?.locationId || "—"}</strong><small>{device.location?.zone || ""}</small></td><td><StatusDot status={device.status} /></td><td><div className="battery"><span style={{ width: `${Math.min(Math.max(device.battery || 0, 0), 100)}%` }} /><em>{device.battery == null ? "—" : `${device.battery}%`}</em></div></td><td>{formatTime(device.lastTelemetryAt || device.lastSeen)}</td><td><span className={`risk-tag ${classForRisk(device.assessment?.riskLevel)}`}>{riskLabel(device.assessment?.riskLevel || "normal")}</span></td><td><button className="row-action" onClick={() => setSelectedDevice(device.deviceId)}>View →</button></td></tr>)}</tbody></table>{!devices.length && <Empty>No ESP32 devices registered yet.</Empty>}</div></section>
      <section className="bottom-grid"><div className="panel assessment-panel"><div className="panel-heading"><div><p className="eyebrow">Decision support</p><h2>Latest assessment</h2></div><span className={`risk-tag ${classForRisk(assessment?.riskLevel)}`}>{riskLabel(assessment?.riskLevel || "normal")}</span></div><div className="assessment-body"><div className="assessment-score"><strong>{assessment?.confidence == null ? "—" : `${Math.round(assessment.confidence * 100)}%`}</strong><span>Model confidence</span></div><div className="assessment-facts"><div><span>Trend</span><strong>{riskLabel(assessment?.trend || "unknown")}</strong></div><div><span>Priority</span><strong>{riskLabel(assessment?.priority || "normal")}</strong></div><div><span>People estimate</span><strong>{assessment?.estimatedAffectedPeople == null ? "Not available" : assessment.estimatedAffectedPeople}</strong></div><div><span>Rescue estimate</span><strong>{assessment?.estimatedRescuePersonnel == null ? "Not available" : assessment.estimatedRescuePersonnel}</strong></div></div></div><p className="disclaimer">Measurements and configured rules are shown separately from ML estimates. Estimates remain unavailable until a validated local model supplies them.</p></div>
        <div className="panel system-panel"><div className="panel-heading"><div><p className="eyebrow">Gateway health</p><h2>System status</h2></div><span className="status-dot online"><i />online</span></div><div className="system-list"><div><span>Database</span><strong>{system?.database || "SQLite"}</strong></div><div><span>Rule engine</span><strong>{system?.ruleEngine?.enabled ? `${system.ruleEngine.configuredRules} configured` : "Disabled"}</strong></div><div><span>ML adapter</span><strong className={system?.ml?.available ? "text-good" : "text-warning"}>{system?.ml?.available ? "Available" : "Unavailable"}</strong></div><div><span>Gateway uptime</span><strong>{system?.uptimeSeconds ? `${Math.floor(system.uptimeSeconds / 3600)}h ${Math.floor((system.uptimeSeconds % 3600) / 60)}m` : "—"}</strong></div></div></div></section>
    </main>
    {selectedDevice && <aside className="drawer-backdrop" onClick={() => setSelectedDevice(null)}><div className="drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">Device detail</span><h2>{selectedDevice}</h2></div><button className="close" onClick={() => setSelectedDevice(null)}>×</button></div><div className="drawer-status"><StatusDot status={selectedStateDevice?.status || deviceDetail?.status} /><span>{selectedStateDevice?.location?.name || deviceDetail?.locationName || "—"}</span></div><h3>Latest telemetry</h3><SensorData data={selectedStateDevice?.telemetry || deviceDetail?.latestTelemetry?.data} /><div className="drawer-divider" /><h3>Processing assessment</h3><div className={`drawer-risk ${classForRisk(selectedStateDevice?.assessment?.riskLevel)}`}>{riskLabel(selectedStateDevice?.assessment?.riskLevel || "normal")}</div><p className="muted">Last seen {formatTime(selectedStateDevice?.lastSeen || deviceDetail?.lastSeen)}</p><h3>Recent history</h3>{history?.rows?.length ? <div className="history-list">{history.rows.map((row) => <div key={row.id}><span>{formatTime(row.timestamp)}</span><b>{Object.keys(row.payload?.data || {}).length} sensor groups</b></div>)}</div> : <Empty>No history available.</Empty>}</div></aside>}
  </div>;
}

createRoot(document.getElementById("root")).render(window.location.pathname.startsWith("/demo") ? <DemoApp /> : <App />);
